---
name: Build examples
on:
  - pull_request
  - push
jobs:
  build_1x1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x:
          - 1
          - 2
        y:
          - 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:openscad/releases
          sudo apt-get update
          sudo apt-get install openscad freebsd-buildutils

      - name: Set environment variables
        run: |

      - name: Build STL files
        run: |
          fmake XY_FLAGS='-D num_x=${{ matrix.x }} -D num_y=${{ matrix.y }}'
